#!/bin/sh
#######################################################################
# Initialization:

#: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/custom}
#. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

if [ -z "$OCF_ROOT" ]; then
    : ${OCF_ROOT=/usr/lib/ocf}
fi

if [ "$OCF_FUNCTIONS_DIR" = ${OCF_ROOT}/resource.d/heartbeat ]; then  # old
        unset OCF_FUNCTIONS_DIR
fi

: ${OCF_FUNCTIONS_DIR:=${OCF_ROOT}/lib/heartbeat}

. ${OCF_FUNCTIONS_DIR}/ocf-binaries
. ${OCF_FUNCTIONS_DIR}/ocf-returncodes
. ${OCF_FUNCTIONS_DIR}/ocf-directories
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

#if test -n "${OCF_FUNCTIONS_DIR}" ; then
#        if test -e "${OCF_FUNCTIONS_DIR}/ocf-shellfuncs" ; then
#                . "${OCF_FUNCTIONS_DIR}/ocf-shellfuncs"
#        elif test -e "${OCF_FUNCTIONS_DIR}/.ocf-shellfuncs" ; then
#                . "${OCF_FUNCTIONS_DIR}/.ocf-shellfuncs"
#        fi
#else
#        if test -e "${OCF_ROOT}/lib/heartbeat/ocf-shellfuncs" ; then
#                . "${OCF_ROOT}/lib/heartbeat/ocf-shellfuncs"
#        elif test -e "${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs"; then
#                . "${OCF_ROOT}/resource.d/heartbeat/.ocf-shellfuncs"
#        fi
#fi

#######################################################################

meta_data() {
	cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="apache-de" version="0.1">
<version>1.0</version>

<longdesc lang="en">
This is a apache Resource Agent. It does absolutely nothing except 
keep track of whether the cyle process is running or not.

NB: Please pay attention to the timeouts specified in the actions
section below. They should be meaningful for the kind of resource
the agent manages. They should be the minimum advised timeouts,
but they shouldn't/cannot cover _all_ possible resource
instances. So, try to be neither overly generous nor too stingy,
but moderate. The minimum timeouts should never be below 10 seconds.
</longdesc>

<shortdesc lang="en">Apache DE resource agent</shortdesc>

<parameters>
<parameter name="homedir" unique="1" required="true">
<longdesc lang="en">
Location of the Apache home directory.
</longdesc>
<shortdesc lang="en">Home Directory</shortdesc>
<content type="string" default="/opt/local/apache2" />
</parameter>
</parameters>

<actions>
<action name="start"        timeout="20s" />
<action name="stop"         timeout="20s" />
<action name="monitor"      timeout="20s" interval="10s" depth="0" />
<action name="validate-all" timeout="20s" />
<action name="meta-data"  timeout="5s"/>
</actions>
</resource-agent>
END
}

#######################################################################

USAGE="Usage: $0 {start|stop|monitor|status|validate-all|meta-data}";


apache_usage() {
	echo $USAGE >&2
}

get_pid_file() {
	PIDFILE="$OCF_RESKEY_homedir/logs/httpd.pid"
}

apache_status() {
	# Monitor _MUST!_ differentiate correctly between running
	# (SUCCESS), failed (ERROR) or _cleanly_ stopped (NOT RUNNING).
	# That is THREE states, not just yes/no.
	get_pid_file	
	if [ -n "$PIDFILE" -a -f $PIDFILE ]; then
		PID=`cat $PIDFILE`
		if [ -n "$PID" ]; then
			if ps -p $PID | grep httpd >/dev/null ; then				
				ocf_log info "httpd daemon running"
				return $OCF_SUCCESS
			else	
				ocf_log error "httpd daemon is not running but pid file exists"
                return $OCF_NOT_RUNNING
			fi
		else
			ocf_log error "PID file empty or doesn't exist!"
			return $OCF_NOT_RUNNING
		fi
	fi

	ocf_log info "cycle daemon is not running"
	return $OCF_NOT_RUNNING
}

apache_start() {
	apache_status
    if [ $rc -eq $OCF_SUCCESS ]; then
		return $OCF_SUCCESS
    elif [ $rc -ne $OCF_NOT_RUNNING ]; then
		ocf_exit_reason "Error. Unknown status."
		exit $OCF_ERR_GENERIC
    fi
	ocf_log info "Starting the DE Apache Service..."
	ocf_run "$OCF_RESKEY_homedir/scripts/startApache"
	ocf_log info "Started the DE Apache Service..."
}

apache_stop() {
	if apache_status; then
		ocf_log info "Stopping the DE Apache Service..."
		ocf_run "$OCF_RESKEY_homedir/scripts/stopApache"
		ocf_log info "Stopped the DE Apache Service..."
	fi
}

apache_validate() {
	apache_status
	return $OCF_SUCCESS
}

#####
#
#MAIN
#
#####

if [ $# -ne 1 ]; then
        apache_usage
        exit $OCF_ERR_ARGS
fi


case $1 in
	start)  
        apache_start
    ;;
    stop)
        apache_stop
    ;;
    status) 
		apache_status
    ;;
    monitor)
		apache_status
    ;;
    validate-all)
        apache_validate
    ;;
    meta-data)    
		meta_data
    ;;
    usage)  
		apache_usage
        exit $OCF_SUCCESS
    ;;
    *)
    	apache_usage
        exit $OCF_ERR_UNIMPLEMENTED
    ;;
esac